services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.3.2
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:7.3.2
        hostname: kafka
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR:

    conduktor-gateway:
        image: conduktor/conduktor-proxy:1.8.2.1-amd64
        hostname: conduktor-gateway
        container_name: conduktor-gateway
        depends_on:
            - kafka
        ports:
            - "6969:6969"
            - "8888:8888"
        environment:
            KAFKA_BOOTSTRAP_SERVERS: kafka:29092
            PROXY_HOST: localhost
            PROXY_PORT_RANGE: 6969:6969
            HTTP_PORT: 8888
            FEATURE_FLAGS_SINGLE_TENANT: "true"
            AUTHENTICATION_AUTHENTICATOR_TYPE: "NONE"
            USER_POOL_TYPE: "JWT"
            USER_POOL_SECRET_KEY: "SECRET"
            ADMIN_API_USERS: "[{username: superUser, password: superUser}]"
            ADMIN_API_SECRET: "OaM4lG+xO5Gz10GB1apZ2XDUuWw/sK1H+XXcgExpYm2YEHgnvEf63q9TJraebD3SQb/JzefcZkUEKz/8V5V+Fg=="
