spring:
    application:
        name: kafka-demo

server:
    port: 9001

kafka:
    bootstrap-servers: localhost:9092
    consumer:
        maxPollIntervalMs: 30000
        maxPollRecords: 500
    outboundTopic: "demo-topic"
